---
- id: tricky_bell_root
  sequence:
  - cond:
      type: flag
      name: counter-dialogs-tricky_bell_root
      what: equal
      value: 1
    after:
      type: flag
      name: test-flag
      value: true
    <tricky_bell>: 'кто здесь? отвечай, кто ты такой? и что тебе здесь надо!?'
    choose:
    - <rathni>: 'привет, звонок! это же я, ратни, не узнал?'
      sequence:
      - <tricky_bell>: "я тебя не знаю, проваливай!"
      - <rathni>: 'ах ты гад! ну и ладно!'
    - <rathni>: 'эээ... ты всегда такой грубый?'
      sequence:
      - <tricky_bell>: "такая уж работа, извиняй. а теперь вали!"
      - <rathni>: 'сам вали!'
    - <rathni>: 'что значт что мне здесь надо? я здесь живу вообще-то!'
      sequence:
      - <tricky_bell>: "... это все меняет ... тогда просто отстань от меня"
      - <rathni>: 'ну лан...'
  - cond: {type: flag, name: counter-dialogs-tricky_bell_root, what: not_equal, value: 1}
    <tricky_bell>: "опять ты? что теперь?"
    choose:
    - <rathni>: 'и тебе привет...'
      sequence:
      - <tricky_bell>: 'я запомнил что ты сказал. теперь проваливай!'
        id_node: tricky_bell_say_goto_hell
      - <rathni>: '(конец диалога)'
    - <rathni>: 'ничего...'
      sequence: tricky_bell_say_goto_hell
    - <rathni>: 'как же ты достал уже!'
      sequence: tricky_bell_say_goto_hell

#- id: barmen_root
#  sequence:
#  #- cond: {type: flag, name: counter-dialogs-barmen_root, value: 1}
#  - if: counter-dialogs-barmen_root == 1
#    sequence:
#    - <barmen>: привет, я бармен-белка, чего тебе налить?
#    - choose:
#      - if: we_already_asked_about_what_to_drink == true
#        sequence:
#        - goto: barmen_choose_drink_root
#      - if: we_already_asked_about_what_to_drink == false
#        after: we_already_asked_about_what_to_drink = true
#        sequence:
#        - <rathni>: привет, а что есть?
#        - <barmen>: у меня есть лучшие сорта разной бормотухи, бодяги и пойла. что тебя интересует?
#        - goto: barmen_choose_drink_root
#  - if: counter-dialogs-barmen_root > 1
#    before: {type: flag, name: barmen_random_phrase_value, value: random(2)}
#    sequence:
#    - if: barmen_random_phrase_value == 0
#      <barmen>: привет, что будешь?
#    - if: barmen_random_phrase_value == 1
#      <barmen>: привет, что пьем сегодня?
#    - if: barmen_random_phrase_value == 2
#      <barmen>: а вот и ты опять! чего налить?
#    - goto: barmen_choose_drink_root

- id: barmen_root
  sequence:
  #- cond: {type: flag, name: counter-dialogs-barmen_root, value: 1}
  - if: counter-dialogs-barmen_root == 1
    side_speech:
    - <barmen>: привет, я бармен-белка, чего тебе налить?
    - <rathni>: привет, а что есть?
      after: we_already_asked_about_what_to_drink = true
    - <barmen>: у меня есть лучшие сорта разной бормотухи, бодяги и пойла. что тебя интересует?
  - if: counter-dialogs-barmen_root > 1
    random_of:
    - <barmen>: привет, что будешь?
    - <barmen>: привет, что пьем сегодня?
    - <barmen>: а вот и ты опять! чего налить?
  - goto: barmen_choose_drink_root

- id: barmen_choose_drink_root
  choose:
  - <rathni>: ну я наверное про бормотуху...
    sequence:  
    - if: we_already_asked_about_what_to_drink == false
      <barmen>: любишь что покрепче? отлично! у меня есть сколопендрова кровь, лавовая бомба ну и змеиная настойка. ну еще есть стеклопротирка, если ты бомжуешь. только эта -- прям здесь не блевать! выходи на улицу!
    - if: we_already_asked_about_what_to_drink == true
      <barmen>: все как обычно -- сколопендрова кровь, лавовая бомба и змеиная настойка. ну и стеклопротирка, да, куда ж без нее...
    - id: choose_bormotuha
      choose:
      - cond: show_once_per_dialog
        <rathni>: надеюсь сколопендрова кровь это не настоящая сколопендрова кровь?
        sequence:
        - <barmen>: да не, она просто такого цвета
        - <rathni>: а из чего ее гонят?
        - <barmen>: из дров. ха-ха-ха! да не, серьезно...
        - <rathni>: ну ладно, как скажешь
        - goto: choose_bormotuha
      - cond: show_once_per_dialog
        <rathni>: что как там лавовая бомба? советуешь?
        sequence:
        - <barmen>: отличная вещь, хит на все времена, очень бодрит. ток поосторожнее там -- ощущение бодряка от нее очень коварно и обманчиво...
        - <rathni>: ого, ладно!
        - goto: choose_bormotuha
      - cond: show_once_per_dialog
        <rathni>: змеиная настойка?
        sequence:
        - <barmen>: ну да, обычная настойка... со змеями... что сказать? еще туда всяких тараканов кладут, вроде...
        - <rathni>: ага, тараканы! это все меняет!
        - <barmen>: многим нравится...
        - <rathni>: так я говорю!
        - goto: choose_bormotuha
      - cond: show_once_per_dialog
        <rathni>: а стеклопротирка как? ничего? она же не для того чтобы стекла протирать, правда? она же просто так называется?
        sequence:
        - <barmen>: давай, утешай себя
        - <rathni>: нууу... то есть да? я вот стекла водой протираю...
        - <barmen>: ну это не вода. не сомневайся! но в качестве утешения могу сказать тебе что я стекла тоже водой протираю
        - <rathni>: а что... она пользуется популяртностью?
        - <barmen>: да, определенно
        - <rathni>: а эти... ее любители... они все еще с нами?... они не покидают нас пока?
        - <barmen>: послушай, я тебя уговаривать не собираюсь
        - <rathni>: ладно, принято
        - goto: choose_bormotuha
      - buy: {money: fish, value: 5, get: shot_of_scolopendra_blood_luquire}
        <rathni>: мне сколопендрову кровь. люблю сколопендр. в смысле дрова люблю...
        #cond: {type: money, subtype: fish, what: >=, value: 5}
        #after:
        #  - {type: change_money, subtype: fish, value: -5}
        #  - {type: add_item, value: shot_of_scolopendra_blood_luquire}
        sequence:
        - id: barmen_sell_something_and_say_random_phrase
          random_of:
          - <barmen>: держи, и постарайся не умереть, хотя бы прям здесь
          - <barmen>: держи, на здоровье
          - <barmen>: желание клиента -- закон!
        - goto: barmen_root
      - buy: {money: fish, value: 6, get: shot_of_lava_blood_luquire}
        <rathni>: давай сюда лавовую бомбу!
        sequence:
        - goto: barmen_sell_something_and_say_random_phrase
      - buy: {money: fish, value: 4, get: shot_of_snake_luquire}
        <rathni>: мне змеиную... с тараканами! да!
        sequence:
        - goto: barmen_sell_something_and_say_random_phrase
      - buy: {money: fish, value: 3, get: shot_of_glass_cleaner_luquire}
        <rathni>: давай стеклопротирку! попробую что-ли... стекла протереть... ей. пора уже... их почистить... ага
        sequence:
        - <barmen>: ток смотри не помри, дорогуша, я буду скучать
        - goto: barmen_root
      - if: {type: money, subtype: fish, what: <, value: 3}
        <rathni>: ой, сорян, я чет не при деньгах сегодня...
        sequence:
        - <barmen>: в долг не даю. даже тебе, красотка
        - goto: barmen_root
      - <rathni>: лан, забудь про бормотуху...
        sequence:
        - goto: barmen_choose_drink_root
  - <rathni>: расскажи мне про бодягу
    #sequence:

  - <rathni>: что насчет пойла?
    #sequence:

  - <rathni>: а что-нибудь безалкогольное есть?
    sequence:
    - <barmen>: да, есть всякий сочек-мочек... ты об этом?
    - <rathni>: ну да, наверное
    - <barmen>: ага, ну там есть сочек... да... ну из фруктов разных... ага, есть еще божественный коктейль "слив унитаза", просто бомба! он из... ну... того что обычно в унитаз сливают... будешь? а, ну еще есть перемолотые жучки... это если ты сколопендра... есть еще искрящаяся вода святого... как там его... ну ты поняла...
    - id: choose_juice_drinks
      choose:
      - if: rathni_knows_abount_murmurla == true
        <rathni>: а из мурмурлы сочек есть?
        sequence:
        - <barmen>: это что еще такое?
        - <rathni>: оо! это божественный фрукт!... я его никогда не видела...
        - <barmen>: хм... ну, я тоже
        - goto: choose_juice_drinks
      - buy: {money: fish, value: 3, get: glass_of_fruit_juice}
        <rathni>: ну мне фруктового сочку тогда
        sequence:
        - <barmen>: как скажешь, спортсмен
        - goto: barmen_root
      - buy: {money: fish, value: 3, get: glass_of_toilet_waste_coctail}
        <rathni>: божественный коктейль! слив унитаза!
        sequence:
        - <barmen>: он твой, золотце # заменить. золота там нет
        - goto: barmen_root
      - buy: {money: fish, value: 4, get: glass_of_bugs_coctail}
        <rathni>: давай мне жучков стакан!
        sequence:
        - <barmen>: о, отнесешь знакомой сколопендре! да?... да?... ты же не...
        - <rathni>: ...
        - <barmen>: ты же не... будешь пить это сама?
        - <rathni>: давай сюда его сейчас!
        - <barmen>: хорошо, хорошо, вот
        - goto: barmen_root
      - buy: {money: fish, value: 2, get: glass_of_saint_water}
        <rathni>: мне стаканчик искрящейся...
        sequence:
        - <barmen>: сладенькая...
        - <rathni>: ммм?
        - <barmen>: держи
        - goto: barmen_root
  - <rathni>: можно мне просто воды...
    sequence:
    - <barmen>: просто воду попей из лужи на улице! вали из моего бара с глаз моих нахрен!
    - choose:
      - <rathni>: чего? сам ты пошел!
        after:
        - {type: relations, with: barmen, value: -1}
        - {type: flag, name: barmen_rathni_water_problem, value: true}
        # end of dialog
      - <rathni>: ладно, ладно! успокойся, чего ты так сразу нервничать?
        sequence:
        - <barmen>: брррр! трисет прям как про воду слышу! не расстраивай меня, слышишь?
        - <rathni>: ладно, не буду!
        - goto: barmen_choose_drink_root
