---
- id: barmen_root
  sequence:
  - <b>: hey
  - <r>: what?
  - <b>: you're bitch
  - id: barmen_root.r_answer
    choose:
    - cond: show_once_per_dialog
      sequence:
      - <r>: what! fuck off!
      - <b>: okay! but try_again
      - goto: r_answer
    - cond: show_once_per_dialog
      sequence:
      - <r>: i gonna kill you!
      - cond: some == 1
        sequence:
        - <b>: im not impressed...
        - goto: lets_continue_here
      - cond: some == 2
        sequence:
        - <b>: oh, i dont take it seriously
        - goto: lets_continue_here
      - cond: some == 3
        sequence:
        - <b>: by the way, my friend agree with me
        - <c>: yeah, i agree!
        - <b>: see?
        - goto: lets_continue_here
      - id: barmen_root.lets_continue_here
        sequence:
        - <r>: and i dont care and kill you anyway!
        - <b>: boooring...
        - goto: r_answer
    - sequence:
      - <r>: quit this shit now...
      - <b>: bye then!
    # choose element is sequence, not a phrase
    # cond applied to sequence, not a phrase!
    # we can fugure it as a 'null' phrase with 'sequence' prop
    - cond: today_is == 'sunday'
      sequence:
      - cond: roll == 1
        sequence:
        - <r>: sunday secret answer
        - <b>: oh, now! i'm sucked
        - goto: r_answer
      - cond: roll == 0
        sequence:
        - <r>: omg again i'm a looser
        - <b>: yeah, you are! and let's try again
        - goto: r_answer

- id: tricky_bell_root
  sequence:
  - cond: {type: flag, name: counter-dialogs-tricky_bell_root, what: ==, value: 1}
    after: {type: flag, name: test-flag, value: true}
    seq:
    - <tricky_bell>: 'кто здесь? отвечай, кто ты такой? и что тебе здесь надо!?'
    - choose:
      - sequence:
        - <rathni>: 'привет, звонок! это же я, ратни, не узнал?'
        - <tricky_bell>: "я тебя не знаю, проваливай!"
        - <rathni>: 'ах ты гад! ну и ладно!'
      - sequence:
        - <rathni>: 'эээ... ты всегда такой грубый?'
        - <tricky_bell>: "такая уж работа, извиняй. а теперь вали!"
        - <rathni>: 'сам вали!'
      - sequence:
        - <rathni>: 'что значт что мне здесь надо? я здесь живу вообще-то!'
        - <tricky_bell>: "... это все меняет ... тогда просто отстань от меня"
        - <rathni>: 'ну лан...'
  - cond: {type: flag, name: counter-dialogs-tricky_bell_root, what: '!=', value: 1}
    seq:
    - <tricky_bell>: "опять ты? что теперь?"
    - choose:
      - seq:
        - <rathni>: 'и тебе привет...'
        - <tricky_bell>: 'я запомнил что ты сказал. теперь проваливай!'
          id_node: tricky_bell_say_goto_hell
        - <rathni>: '(конец диалога)'
      - seq:
        - <rathni>: 'ничего...'
        - goto: tricky_bell_say_goto_hell
      - seq:
        - <rathni>: 'как же ты достал уже!'
        - goto: tricky_bell_say_goto_hell
