---
- id: barmen_root
  sequence:
  - <b>: hey
  - <r>: what?
  - <b>: you're bitch
  - id: r_answer
    choose:
    - <r>: what! fuck off!
      cond: show_once_per_dialog
      sequence:
      - <b>: okay! but try_again
      - goto: r_answer
    - <r>: i gonna kill you!
      cond: show_once_per_dialog
      sequence:
      - cond: some == 1
        sequence:
        - <b>: im not impressed...
        - goto: lets_continue_here
      - cond: some == 2
        sequence:
        - <b>: oh, i dont take it seriously
        - goto: lets_continue_here
      - cond: some == 3
        sequence:
        - <b>: by the way, my friend agree with me
        - <c>: yeah, i agree!
        - <b>: see?
        - goto: lets_continue_here
      - id: lets_continue_here
        sequence:
        - <r>: and i dont care and kill you anyway!
        - <b>: boooring...
        - goto: r_answer
    - <r>: quit this shit now...
      sequence:
      - <b>: bye then!
    # choose element is sequence, not a phrase
    # cond applied to sequence, not a phrase!
    # we can fugure it as a 'null' phrase with 'sequence' prop
    - cond: today_is == 'sunday'
      sequence:
      - cond: roll == 1
        sequence:
        - <r>: sunday secret answer
        - <b>: oh, now! i'm sucked
        - goto: r_answer
      - cond: roll == 0
        sequence:
        - <r>: omg again i'm a looser
        - <b>: yeah, you are! and let's try again
        - goto: r_answer
